; https://projecteuler.net/problem=12
; Highly divisible triangular number

; Problem 12
; The sequence of triangle numbers is generated by adding the natural numbers.
; So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
; The first ten terms would be:

; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

; Let us list the factors of the first seven triangle numbers:

;  1: 1
;  3: 1,3
;  6: 1,2,3,6
; 10: 1,2,5,10
; 15: 1,3,5,15
; 21: 1,3,7,21
; 28: 1,2,4,7,14,28

; We can see that 28 is the first triangle number to have over five divisors.

; What is the value of the first triangle number to have over five hundred
; divisors?

(use 'clojure.test)

(defn euler12
  "it returns the value of the first triangle number to have over n divisors."
  ([] (euler12 500))
  ([n]
    (letfn [(triangle-numbers []
              (rest (for [x (range)]
                      (reduce + (range (inc x))))))
            (divisors [k]
              (filter #(zero? (mod k %)) (range 1 (inc k))))]

      (first (filter #(> (count (divisors %)) n) (triangle-numbers))))))

(is (= 28 (euler12 5)))
(is (= 76576500 (euler12)))
